### ISSUE TITLE
Unable to run role on Mac OS Sierra

### ISSUE THREAD

**Issue by NileshGule** [gantsign/ansible-role-intellij-plugins#31]
I tried to use the role on macOS Sierra with Ansible version **2.3.1.0**. The role gives an error saying undefined variable **'ansible_local'**

Let me know if any specific system wis or playbook wide variable needs to be defined.

I have defined the required variables for the role in my playbook as
 - role: gantsign.intellij-plugins
       users:
         - username: "{{general.user_name}}"
          intellij_plugins_intellij_home: '/Applications/IntelliJ IDEA CE.app/Contents'
          intellij_plugins_intellij_user_dirname: '.IdeaIC2017.1'
          intellij_plugins:
         - CheckStyle-Idea

**Comment by freemanjp** [comment]
This is because you've put `intellij_plugins_intellij_home` and `intellij_plugins_intellij_user_dirname` under the user; it should be directly under the role e.g.:

```yaml
- role: gantsign.intellij-plugins
  intellij_plugins_intellij_home: '/Applications/IntelliJ IDEA CE.app/Contents'
  intellij_plugins_intellij_user_dirname: '.IdeaIC2017.1'
  users:
    - username: "{{general.user_name}}"
      intellij_plugins:
        - CheckStyle-Idea
```

FYI: `ansible_local` is the root for Ansible facts, in this case the ones set by https://github.com/gantsign/ansible-role-intellij if you're using it to install IntelliJ.

That said, I don't have a Mac so I've no idea whether this role will work on a Mac, and [Molecule](https://molecule.readthedocs.io/en/master/index.html) (the tool I use for testing) doesn't support Mac either.
